# Ansible inventory - Auto-generated by Terraform
# Do not edit manually. Re-run 'terraform apply' to re-generate

[all:vars]
ansible_ssh_private_key_file=${ssh_key_path}
ansible_python_interpretor=/usr/bin/python3
ansible_host_key_checking=false

[servers]
%{ for name, inst in ubuntu ~}
${ name } ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}

%{ for name, inst in centos ~}
${ name } ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}

%{ for name, inst in amazon ~}
${ name } ansible_host=${inst.public_ip} ansible_user=${inst.user}
%{ endfor ~}
